[package]
name = "flechs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.65"
num = "0.4.0"
thiserror = "1.0.37"
